### PR TITLE
V2 option support

### PR DESCRIPTION
**Pull request by lbwniubi777**

### CODE REVIEW

**Comment by carleeno** [comment]
Thanks for the pr! I'm currently camping with limited signal, I'll review this late Monday.

**Comment by carleeno** [comment]
Do you think we should add config/option flow validation for if a user tries to customize the new speaker boost or style options while using a v1 model? It seems the api doesn't complain if passing those params when using an older model, but I'm trying to think of a way to hint that the new options only apply to v2.

**Comment by lbwniubi777** [comment]
> Do you think we should add config/option flow validation for if a user tries to customize the new speaker boost or style options while using a v1 model? It seems the api doesn't complain if passing those params when using an older model, but I'm trying to think of a way to hint that the new options only apply to v2.

I am sorry as I am a beginner and may have missed some things. I may not be able to make significant changes. I have made some updates that should take effect.

**Comment by carleeno** [comment]
> I am sorry as I am a beginner and may have missed some things. I may not be able to make significant changes. I have made some updates that should take effect.

No worries! we all start somewhere. See if you can fix the failing lint and tests, and you could even run the local HA devcontainer to make sure it works like you expect:

- open this repo's folder in vs code, it should prompt you if you want to open in a dev container. if it doesn't prompt you, make sure you have the dev container extension installed and use the command pallet to "reopen in dev container"
- after it's finished building the dev container, in the integrated terminal run `./scripts/setup`
- then you can run the tests with `pytest`, and link with `./scripts/lint`

**Comment by lbwniubi777** [comment]
> > I am sorry as I am a beginner and may have missed some things. I may not be able to make significant changes. I have made some updates that should take effect.
> 
> No worries! we all start somewhere. See if you can fix the failing lint and tests, and you could even run the local HA devcontainer to make sure it works like you expect:
> 
> * open this repo's folder in vs code, it should prompt you if you want to open in a dev container. if it doesn't prompt you, make sure you have the dev container extension installed and use the command pallet to "reopen in dev container"
> * after it's finished building the dev container, in the integrated terminal run `./scripts/setup`
> * then you can run the tests with `pytest`, and link with `./scripts/lint`

Thank you for your guidance! I have learned a lot.

**Review by carleeno — APPROVED** [review]
Thanks!

**Pull request merged**
